POST http://localhost:3000/api/v1/workouts HTTP/1.1
content-type: application/json


{
  "name": "Core Busterx",
  "mode": "AMRAP 201",
  "equipment": [
    "rack",    
    "abmat"
  ],
  "exercises": [
    "16 toes to bars",
    "100 thrusters",
    "30 abmat sit-ups"
  ],
  "trainerTips": [
    "Split your toes to bars into two sets maximum",    
    "Take the abmat sit-ups as a chance to normalize your breath"
  ]
}
